### ISSUE TITLE
cnn-cbir-benchmark/fc_retrieval/src/extract_features.py 17行

### ISSUE THREAD

**Issue by yihuawei** [willard-yuan/cnn-cbir-benchmark#12]
请教一下，为什么要用d减去这个数组呢？如果输入的是四通道图像的话，我该如何修改这个命令呢？
d -= np.array((104.00698793,116.66876762,122.67891434))

谢谢

**Comment by willard-yuan** [comment]
这个是减去imageNet图像的均值。如果是四通道图像，简单的处理方式是丢掉非rgb的通道，如果是不能丢的话，可以先训练模型。
