### ISSUE TITLE
关于windows下生成lmdb文件

### ISSUE THREAD

**Issue by uiui816** [willard-yuan/cnn-cbir-benchmark#13]
您好，看了您的博客，干货很多，谢谢分享！
有个问题想请教一下，我是在windows下来完成这个工程的，在利用train.txt生成对应的lmdb文件时出现一个问题，就是数据集中原来存在.gif格式的图片，但是在生成lmdb文件时无法打开这种格式的文件，想问一下是应该再生成train.txt文件之前先提出掉这一类的图片，还是在生成lmdb文件时需要对什么参数进行设置，盼望您的回复！，

**Comment by willard-yuan** [comment]
@uiui816 我觉得最快的方式是你在生成train.txt文件之前先剔除掉，或者在生成的时候，就把gif格式转成jpeg或者png格式，你可以搜一下gif格式转成jpeg或者png格式的方法。

**Comment by uiui816** [comment]
@willard-yuan 好的，我明白了。谢谢您！还有一个问题，我想问一下train_val.prototxt这个文件时在原始模型的 .prototxt文件上进行修改的吗？我能在哪里找到该文件呢？

**Comment by willard-yuan** [comment]
@uiui816 你问的是vggNet的prototxt文件吗？这个我好像是从VGG的官网上下载的，你直接用这个没啥问题，我都验证训练过好多次了，没有问题。

**Comment by uiui816** [comment]
@willard-yuan 嗯，可是我看您主页上的只有开头输入部分和输出部分，github上您的工程文件夹里好像也没有呢？

**Comment by willard-yuan** [comment]
@uiui816 fc提特征模型文件在这里[fc_vgg16.prototxt](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/fc_retrieval/model/fc_vgg16.prototxt)。

**Comment by willard-yuan** [comment]
@uiui816 我先关了，有问题再打开。
