### ISSUE TITLE
请问在 vlad_retrieval 的 vlad.py 中 上一级的models 文件夹在哪里，是自己手动创建吗？可是里面的文件又是怎么生成的呢

### ISSUE THREAD

**Issue by ghost** [willard-yuan/cnn-cbir-benchmark#17]
h5f = h5py.File('./models/vlad_128_8192.h5', 'w')
# load PCA and KMeans model
centroids = np.load('./models/centroids_data.npy')
pca_transform = np.load('./models/pca_data.npy')
mean = np.load('./models/mean_data.npy')

**Comment by willard-yuan** [comment]
@tianlanli 对于vlad或者fv，运行的步骤如下:

1. 先使用[extract_hesaff.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/fv_retrieval/src/extract_hesaff.py)抽取oxford building dataset的所有图片的局部特征;
2. 使用[kmeans.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/kmeans.py)获取PCA降维矩阵，以及聚类获取codebook，文件会保存在model里面；
3. 用[vlad.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/vlad.py)对oxford building dataset里的图片进行vlad特征表示；
4. 使用[brute.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/brute.py)计算在oxford building dataset上的MAP。

整体步骤是这样的，希望可以解决你的问题。

**Comment by ghost** [comment]
> @tianlanli 对于vlad或者fv，运行的步骤如下:
> 
> 1. 先使用[extract_hesaff.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/fv_retrieval/src/extract_hesaff.py)抽取oxford building dataset的所有图片的局部特征;
> 2. 使用[kmeans.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/kmeans.py)获取PCA降维矩阵，以及聚类获取codebook，文件会保存在model里面；
> 3. 用[vlad.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/vlad.py)对oxford building dataset里的图片进行vlad特征表示；
> 4. 使用[brute.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/vlad_retrieval/src/brute.py)计算在oxford building dataset上的MAP。
> 
> 整体步骤是这样的，希望可以解决你的问题。

非常感谢
