### ISSUE TITLE
Oxford数据集如何在CNN网络训练问题

### ISSUE THREAD

**Issue by Sunwzh** [willard-yuan/cnn-cbir-benchmark#2]
您好，我一直在关注您的博客，看您的博客让我受益很多。最近有个问题很困惑，想向您咨询一下。
类似于OXford5K和Paris6K数据集都是按照关键字从网络中爬取的，就Paris6K来说，一共按照12个关键字，从网络中爬取的，一共有11个类，每类给出了5张query图片，每个query图片还给出了对应的查询结果图片集。那么我们微调或者训练CNN的时候，是应该直接按照12个类按原始数据划分成训练集测试集训练，还是只使用他提供的查询结果按照11个类进行训练呢？

**Comment by willard-yuan** [comment]
小伙子，问了个好问题，哈哈。如果你要微调网络的话，不能用Paris6K数据集本身，你需要用别的数据集，比如可以用landmark数据集，landmark数据集下载请参考：[这里](https://github.com/willard-yuan/cnn-cbir-benchmark/tree/master/fc_retrieval)

**Comment by Sunwzh** [comment]
这样啊。。怪不得总觉得之前做的有点怪怪的。。还有您博客里面做的那个Oxford的实验mAP是用的他给的那个查询结果然后使用查询返回的所有的查询结果计算的么。。还是查询一部分，比如只返回100张计算的

**Comment by willard-yuan** [comment]
是所有的查询结果，计算mAP的时候，返回所有排序的结果，然后用那个提供的计算mAP的代码就可以算得oxford上的mAP

**Comment by Sunwzh** [comment]
好的，非常感谢！
