### ISSUE TITLE
可以分享一下您做好的train/val数据集或者lmdb文件么。

### ISSUE THREAD

**Issue by Sunwzh** [willard-yuan/cnn-cbir-benchmark#3]
按照您博客里的步骤，做那个数据增强的时候。需要keras，我这电脑老是装不上keras库。。可以分享一下您做好的train/val数据集或者lmdb文件么。

**Comment by willard-yuan** [comment]
@Sunwzh 这个train/val的数据集太大了，我相信你能装上的。装好后用这个脚本[check_image.py](https://github.com/willard-yuan/mykit/blob/master/python/dl/check_image.py)检测一下数据集是否可读，这个landmark里面有一些图片是不可读的，，所以用这个可以检查出哪些是不可读的图片；在用[keras_imgAug.py](https://github.com/willard-yuan/mykit/blob/master/python/dl/keras_imgAug.py)这个脚本就可以获得做完增强的数据集。

**Comment by Sunwzh** [comment]
装上了，哈哈
