### ISSUE TITLE
您好，您文件夹提供的那个compute_ap文件好像没有办法打开。

### ISSUE THREAD

**Issue by Sunwzh** [willard-yuan/cnn-cbir-benchmark#4]
cnn-cbir-benchmark/fc_retrieval/tools/compute_ap这个文件好像是没办法打开的

**Comment by willard-yuan** [comment]
@Sunwzh 抱歉才注意到。compute_ap是计算MAP的二进制文件，是从compute_ap.cpp编译过来的，我已经在readme里面把它的编译过程做了说明。

**Comment by Sunwzh** [comment]
没事，谢谢您，我已经在Oxford数据集的网站上看到了。

**Comment by Sunwzh** [comment]
我还想问您一下，因为我看很多哈希算法在做recall-precision评价时使用的都是原欧式空间中查询样本的近邻做的，包括您提供的hash-baseline库中也是这样做的。如果我想对Oxford数据集做recall-precision等评价，是应该使用原欧式空间中查询样本的近邻，还是用数据集本身提供的groundtruth呢？

**Comment by willard-yuan** [comment]
Oxford这个数据集适合评估object retrieval或者instance retrieval，评估的时候要用数据集本身提供的groundtruth。

**Comment by Sunwzh** [comment]
好的，谢谢~
