### ISSUE TITLE
map大于1

### ISSUE THREAD

**Issue by Jay-Zen** [willard-yuan/cnn-cbir-benchmark#5]
你好，直接跑发现有的图片ap指标大于1。

**Comment by willard-yuan** [comment]
@Jay-Zen 抱歉现在才看到，原因找到了？你是不是哪里有问题，按照这个代码来跑，是不应该存在这样的问题的。

**Comment by Jay-Zen** [comment]
我刚发现了，是因为feat文件夹里面多存了一遍特征导致的重复加载和计算。多线程跑了一次，然后没用多线程也跑了一次。保存了两次全部特征。代码写的很好，我刚开始做图像检索，学习了。

**Comment by willard-yuan** [comment]
哈哈，每次跑之前，最好把feat文件夹里面的特征删掉

**Comment by Jay-Zen** [comment]
嗯嗯，好嘞。我打算再添加些显示功能。
你的blog好像没见到留言功能。请教下，如果实际使用的话，在检索之前要对图片先做检测吧，针对检测出的目标框图再做检索吧？
如果这样那么就需要两套标定数据集吧。第一套：检测标定大图中物体框，不需要标细类别。第二套：把物体框获取出来构建图片集，当然也可以加入其他现有图片集或者爬虫图片。所有图片集再标定多种物体类别用于训练检索底库。

**Comment by willard-yuan** [comment]
你添加的一些功能，如果觉得好的话，可以提交一个pull request，这样就可以让这个检索的对比框架做得越来越完善。

我博客有Disqus评论，需要科学上网才能显示评论。

一般而言，如果要做instance retrieval的话，最好的方式还是先做一个检测，然后在检索框里面提取特征，在进行检索了。典型的如人脸检索，行人再识别等。
