### ISSUE TITLE
每次跑指标都不一样，查询过程中有存在随机性吗？

### ISSUE THREAD

**Issue by Jay-Zen** [willard-yuan/cnn-cbir-benchmark#6]
情况如下，
在特征保存后，运行brute.py
跑一次：
keble_000227.jpg, 0.605056  ... ...
map:0.581817141818
跑另一次：
keble_000227.jpg, 0.633040  ... ...
map:0.589312810803
也看了下查询结果tmp.txt，发现每次排序结果也不同。

请教下
针对以上情况，是什么原因导致结果不同呢？
以下哪个过程有随机性能呢？ 好像都没有吧
原始特征 ->( PCA -> cosin_distance) -> (QE -> cosin_distance) -> do_rerank

谢谢

**Comment by willard-yuan** [comment]
应该不会出现这种问题，你不要做PCA，也不要做QE，也不要做rerank，测一下结果看看是否是不变的。

**Comment by Jay-Zen** [comment]
发现是PCA会导致结果不同，还需再细分析。结果如下
('do_QE', False)
('do_pca', False)
('do_rerank', False)
相同，第一次： 0.574992023636，第二次0.574992023636

('do_QE', False)
('do_pca', False)
('do_rerank', True)
相同： 0.497666889091， 0.497666889091

('do_QE', True)
('do_pca', False)
('do_rerank', True)
相同： 0.587733981818，0.587733981818


('do_QE', True)
('do_pca', False)
('do_rerank', False)
相同：0.654556563636  看来do_rerank 会使得效果更差了


('do_QE', True)
('do_pca', True)
('do_rerank', False)
0.658492376364

('do_QE', True)
('do_pca', True)
('do_rerank', True)
不同， 第一次0.58964818， 第二次 0.594604098182

**Comment by willard-yuan** [comment]
do_rerank这个不要用，我回去了把它删了，这个do_rerank用的方法不怎么work。

**Comment by Jay-Zen** [comment]
PCA之前应该是固定的吧。PCA之后试了应该是不影响结果的。
那PCA为什么会导致每次结果不一样呢？ 我还没搞清楚，你了解吗？

**Comment by willard-yuan** [comment]
因为算PCA的时候，每次算出来的值会存在细小的差异，这种差异可以忽略。你可以一次算好PCA后，下次用这个算好的PCA就可以。
