### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by 0-LL-0** [willard-yuan/cnn-cbir-benchmark#7]
Can you add the time comparisons for each algorithm?

**Comment by willard-yuan** [comment]
@CBIR-LL Sorry for later reply. There feature extraction time is usually fast by using GPU. I wonder you want to know the feature index time. It's a ANN search problem. For ANN search, you can refer to my blog post [图像检索：再叙ANN Search](http://yongyuan.name/blog/ann-search.html).
