### ISSUE TITLE
RMAC extractor

### ISSUE THREAD

**Issue by ahyunSeo** [willard-yuan/cnn-cbir-benchmark#8]
Does evaluation on RMAC part finished?
I could not understand the README and the issues,
but I was looking for a python ver rmac extractor.
Am I on the right spot?

**Comment by willard-yuan** [comment]
Yes. It has finished. You can extract RMAC feature by using [oxford5k_feats_extract.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/rmac_retrieval/src/oxford5k_feats_extract.py), and run [brute.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/rmac_retrieval/src/brute.py) you can get the MAP.

**Comment by ahyunSeo** [comment]
Thanks. I have an additional question. Is there any reason you don't do PCA when extracting the feature? I only see PCA in brute.py. Did I miss something?

**Comment by willard-yuan** [comment]
It's original feature. It's a good idea to save the original feature since it's convenient for you to test the PCA reduction effect on the feature, such as 256d, 128d.

**Comment by ahyunSeo** [comment]
Thanks for your quick reply. Have a nice day!
