### ISSUE TITLE
rmac_retrieval prototxt and model

### ISSUE THREAD

**Issue by ahyunSeo** [willard-yuan/cnn-cbir-benchmark#9]
Hello,

I'm new to caffe (only have experience to pytorch or tensorflow etc).
Is is OK to use models and prototxt where you stated in **fc_retrieval/README.md**?
I'm planning to download model with the link in the README, and use prototxt in fc_retreival/model dir.
Correct me If I'm going to the wrong direction.
Thanks again.

Ahyun

**Comment by willard-yuan** [comment]
@ahyunSeo You get the point and on the right way.
